### ISSUE TITLE
Roadmap to 0.0.1

### ISSUE THREAD

**Issue by angusmoore** [angusmoore/Symele.jl#1]
These are tasks I want to complete before tagging a first version with julia's package manager.

- [ ] Arbitrary order perturbation
- [ ] Checking estimation code works correctly. It is currently a rush job.
    * [ ] Likely worth interfacing with existing JuliaStats packages for MLE and MCMC.
- [ ] Ensure all exported functions have docstrings
- [ ] Ensure documentation includes MWE and is sufficiently clear for new users.
- [ ] Better than 90% test coverage.
